# frozen_string_literal: true

# Generated by the tacit release workflow — do not edit by hand.
class Tacit < Formula
  desc "CLI + TUI for managing AWS SSM Parameter Store secrets"
  homepage "https://github.com/mtab/tacit"
  version "0.1.0"
  license :cannot_represent # proprietary

  on_macos do
    on_arm do
      url "https://github.com/mTABNPD/homebrew-tap/releases/download/tacit-v0.1.0/tacit-v0.1.0-darwin-arm64.tar.gz"
      sha256 "7f7fce82882d8da868213e37d49cb3780f940ae904e56634c2efd2ade13b95ea"
    end
    on_intel do
      url "https://github.com/mTABNPD/homebrew-tap/releases/download/tacit-v0.1.0/tacit-v0.1.0-darwin-amd64.tar.gz"
      sha256 "07bb471b9e7c54daec0d0160fd2ee326910ef93e009b10a6d525d2385242937a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mTABNPD/homebrew-tap/releases/download/tacit-v0.1.0/tacit-v0.1.0-linux-arm64.tar.gz"
      sha256 "1ad9265560032f559c90b16a61ea74acf332f6905a934565a6e01ab0ff54cb64"
    end
    on_intel do
      url "https://github.com/mTABNPD/homebrew-tap/releases/download/tacit-v0.1.0/tacit-v0.1.0-linux-amd64.tar.gz"
      sha256 "7c68f8a317781a5567dc694c36dbafe1c158904474628d9d176f9a8d540ebb57"
    end
  end

  def install
    bin.install "tacit"
  end

  test do
    assert_match "v0.1.0", shell_output("#{bin}/tacit --version")
  end
end
